pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r css/style.css .public
    - cp -r index.html .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
